local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("cpp", {
  s("acm_gcc", {
    t({
      "#include <bits/stdc++.h>",
      "using namespace std;",
      "",
      "using ll = long long;",
      "using ull = unsigned long long;",
      "using pii = pair<int, int>;",
      "using pll = pair<ll, ll>;",
      "using vi = vector<int>;",
      "using vll = vector<ll>;",
      "",
      "constexpr int INF = 0x3f3f3f3f;",
      "constexpr ll LINF = 0x3f3f3f3f3f3f3f3fLL;",
      "constexpr int MOD = 1e9 + 7;",
      "",
      "// ---------- helpers ----------",
      "template <class T>",
      "bool chmax(T& a, const T& b) {",
      "    if (a < b) {",
      "        a = b;",
      "        return true;",
      "    }",
      "    return false;",
      "}",
      "",
      "template <class T>",
      "bool chmin(T& a, const T& b) {",
      "    if (a > b) {",
      "        a = b;",
      "        return true;",
      "    }",
      "    return false;",
      "}",
      "",
      "ll qpow(ll a, ll b, ll mod = MOD) {",
      "    ll res = 1;",
      "    while (b) {",
      "        if (b & 1) res = res * a % mod;",
      "        a = a * a % mod;",
      "        b >>= 1;",
      "    }",
      "    return res;",
      "}",
      "",
      "// ---------- debug ----------",
      "#ifdef LOCAL",
      "template <class T>",
      "void _debug(const T& x) { cerr << x; }",
      "",
      "template <class T1, class T2>",
      "void _debug(const pair<T1, T2>& p) {",
      "    cerr << '{';",
      "    _debug(p.first);",
      "    cerr << \", \";",
      "    _debug(p.second);",
      "    cerr << '}';",
      "}",
      "",
      "template <class T>",
      "void _debug(const vector<T>& v) {",
      "    cerr << '[';",
      "    for (int i = 0; i < (int)v.size(); i++) {",
      "        _debug(v[i]);",
      "        if (i + 1 != (int)v.size()) cerr << \", \";",
      "    }",
      "    cerr << ']';",
      "}",
      "",
      "#define debug(x) do { cerr << #x << \" = \"; _debug(x); cerr << '\\n'; } while (0)",
      "#else",
      "#define debug(x) ((void)0)",
      "#endif",
      "",
      "// ---------- solve ----------",
      "void solve() {",
      "    ",
    }),
    i(1),
    t({
      "",
      "}",
      "",
      "int main() {",
      "    ios::sync_with_stdio(false);",
      "    cin.tie(nullptr);",
      "",
      "    int t = 1;",
      "    // cin >> t;",
      "    while (t--) solve();",
      "",
      "    return 0;",
      "}",
    }),
  }),
})
